Map<String, List<String>> studentCourses = <String, List<String>>{
  'SD': [
    'mathematics',
    'indonesian language',
    'english language',
    'natural sciences',
    'social sciences',
    'traditional language',
    'art and culture',
    'pancasila education',
    'religion education',
    'sports',
  ],
  'MI': [
    'mathematics',
    'indonesian language',
    'english language',
    'arabic language',
    'traditional language',
    'fiqh',
    'aqidah akhlak',
    'quran hadith',
    'natural sciences',
    'pancasila education',
    'social sciences',
    'art and culture',
    'sports',
  ],
  'SMP': [
    'mathematics',
    'natural sciences',
    'social sciences',
    'indonesian language',
    'english language',
    'traditional language',
    'pancasila education',
    'religion education',
    'art and culture',
    'sports',
    'information technology and computer',
  ],
  'MTS': [
    'mathematics',
    'natural sciences',
    'social sciences',
    'indonesian language',
    'english language',
    'traditional language',
    'pancasila education',
    'art and culture',
    'sports',
    'fiqh',
    'aqidah akhlak',
    'quran hadith',
    'arabic language',
  ],
  'SMA': [
    'mathematics',
    'physics',
    'chemistry',
    'biology',
    'indonesian language',
    'english language',
    'traditional language',
    'pancasila education',
    'religion education',
    'art and culture',
    'sports',
    'geography',
    'economics',
    'history',
    'acounting',
    'sociology',
  ],
  'SMK': [
    'mathematics',
    'natural sciences',
    'indonesian language',
    'english language',
    'traditional language',
    'pancasila education',
    'religion education',
    'information technology and computer',
    'entrepreneurship',
    'business and marketing',
    'engineering',
    'agriculture',
    'health',
    'hospitality',
    'tourism',
    'media and broadcasting',
    'automotive',
    'culinary',
    'fashion',
    'crafts and arts',
  ],
  'MA': [
    'mathematics',
    'natural sciences',
    'social sciences',
    'indonesian language',
    'english language',
    'traditional language',
    'pancasila education',
    'art and culture',
    'sports',
    'fiqh',
    'aqidah akhlak',
    'quran hadith',
    'arabic language',
  ],
  'MAK': [
    'mathematics',
    'natural sciences',
    'social sciences',
    'indonesian language',
    'english language',
    'traditional language',
    'pancasila education',
    'art and culture',
    'sports',
    'fiqh',
    'aqidah akhlak',
    'quran hadith',
    'arabic language',
    'information technology and computer',
    'entrepreneurship',
    'business and marketing',
    'engineering',
    'agriculture',
    'automotive',
    'health',
    'hospitality',
    'tourism',
  ],
};
